openapi: 3.0.1
info:
  title: Ideapack API
  description: 'This is an API of Ideapack services.'
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
paths:
  /orders:
    get:
      tags:
        - order
      summary: Returns the shipment order list
      description: Returns the shipment order list
      operationId: getOrders
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderList'
  /order:
    put:
      tags:
        - order
      summary: Save/update a shipment order
      operationId: saveOrUpdateOrder
      requestBody:
        content:
          'application/json':
            schema:
              $ref: '#/components/schemas/Order'
        required: true
      responses:
        200:
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Order'
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        400:
          description: Invalid Order
          content: {}
      x-codegen-request-body-name: body
  /order/{orderId}:
    get:
      tags:
        - order
      summary: Find shipment order by Id
      operationId: getOrderById
      parameters:
        - name: orderId
          in: path
          description: Id of shipment order that needs to be fetched
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: successful operation
          content:
            application/xml:
              schema:
                $ref: '#/components/schemas/Order'
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        400:
          description: Invalid Id supplied
          content: {}
        404:
          description: Shipment order not found
          content: {}
    delete:
      tags:
        - order
      summary: Delete shipment order by Id
      operationId: deleteOrder
      parameters:
        - name: orderId
          in: path
          description: Id of the order that needs to be deleted
          required: true
          schema:
            type: integer
            format: int64
      responses:
        400:
          description: Invalid Id supplied
          content: {}
        404:
          description: Shipment order not found
          content: {}
components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: string
        supplierOrderId:
          type: string
        supplier:
          type: string
          description: 'Service supplier company. Ex: UPS'
        sender:
          type: string
        recipient:
          type: string
        quantity:
          type: integer
          format: int32
        shipDate:
          type: string
          format: date-time
        deliveryDate:
          type: string
          format: date-time
        status:
          type: string
          description: Order Status
          enum:
            - placed
            - approved
            - delivered
        complete:
          type: boolean
          default: false
        shipment:
          $ref: '#/components/schemas/Shipment'
      xml:
        name: Order
    OrderList:
      type: object
      properties:
        orders:
          type: array
          items:
            $ref: '#/components/schemas/Order'
    Shipment:
      type: object
      properties:
        id:
          type: string
        trackingData:
          type: string
          description: The delivery address
        shipmentId:
          type: string
        status:
          type: string
          description: Shipping Status
        lastUpdate:
          type: string
          format: date-time
        sender:
          type: string
          description: The Sender name
        pickupLocation:
          type: string
          description: The Pickup location
        deliveryEstimate:
          type: string
          format: date-time
        recipient:
          type: string
          description: The Recipient name
        recipientPhone:
          type: string
          description: The Recipient phone number
        destination:
          type: string
          description: The delivery address
        deliveryDate:
          type: string
          format: date-time
        shippingPrice:
          type: number
